before:
  hooks:
    - go mod download
    - go test -v ./...
builds:
  - binary: nitro
    id: nitro
    main: ./cmd/nitro/main.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags: -s -w -X github.com/craftcms/nitro/command/version.Version={{.Version}}
archives:
  - name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"
    id: nitro
    builds:
      - nitro
    replacements:
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
dockers:
  - image_templates:
      - craftcms/nitro-proxy
  dockerfile: Dockerfile
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  github:
    owner: craftcms
    name: nitro
brews:
  - tap:
      owner: craftcms
      name: nitro-brew
    folder: Formula
    homepage:  https://goreleaser.com
    description: Deliver Go binaries as fast and easily as possible
    license: MIT
    test: |
      system "#{bin}/nitro -v"
    dependencies:
    - name: go
    install: |-
      bin.install "nitro"
      bash_completion.install "completions/nitro.bash" => "nitro"
      zsh_completion.install "completions/nitro.zsh" => "_nitro"
