before:
  hooks:
    - go mod download
    - go test -v ./...
builds:
  - binary: nitro
    id: nitro
    main: ./cmd/nitro/main.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags: -s -w -X github.com/craftcms/nitro/command/version.Version={{.Version}}
archives:
  - name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"
    id: nitro
    builds:
      - nitro
    replacements:
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  prerelease: auto
  github:
    owner: craftcms
    name: nitro
brews:
  - tap:
      owner: craftcms
      name: homebrew-nitro
    folder: Formula
    homepage:  https://getnitro.sh/
    description: Speedy local dev environment for Craft CMS. Powered by Docker.
    license: MIT
    test: |
      system "#{bin}/nitro --version"
    install: |-
      bin.install "nitro"
