blackfire:
  client: 123456
  secret: 123456
databases:
  - engine: mysql
    version: "8.0"
    port: "3306"
  - engine: mariadb
    version: "10"
    port: "33061"
  - engine: postgres
    version: "11"
    port: "5432"
sites:
  - hostname: example.nitro
    aliases:
      - test.example.nitro
      - local.exampleproject.com
    webroot: ~/dev/craft-example/web
    php: 7.2
  - hostname: plugins.nitro
    aliases:
      - plugins.test
      - local.plugins.craftcms.com
    webroot: ~/dev/craftnet/web
    php: 7.2
